In [8]:
import pandas as pd #importamos librerias pandas

In [9]:
data = pd.read_csv("amazon_product.csv") # usamos la funcion read_csv para leer el archivo csv y lo guardamos en la variable
data

,Unnamed: 0,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
0,0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,...,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
1,1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,...,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False,Only 7 left in stock - order soon.,NaN,NaN
2,2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,...,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN
3,3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,...,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True,NaN,NaN,NaN
4,4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,...,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,59,B0D6LWXK1R,Greatish Hits: I Followed My Dreams and My Dre...,$34.98,NaN,USD,NaN,0,https://www.amazon.com/dp/B0D6LWXK1R,https://m.media-amazon.com/images/I/815otxMW0i...,...,False,False,False,False,50+ bought in past month,FREE delivery on $35 shipped by Amazon.This ti...,False,NaN,NaN,NaN
60,60,B0CLKQF5HR,Swan Song,$14.99,$30.00,USD,4.4,14471,https://www.amazon.com/dp/B0CLKQF5HR,https://m.media-amazon.com/images/I/71dSn3QCY6...,...,True,False,False,False,Print List Price:,Available instantly,False,NaN,NaN,NaN
61,61,B0BZFHK12K,Bluey: Let&#x27;s Play!,$0.00,NaN,USD,3.5,270,https://www.amazon.com/dp/B0BZFHK12K,https://m.media-amazon.com/images/I/617GUqQEIC...,...,False,False,False,False,"Jul 7, 2023",Available instantly on compatible devices,False,NaN,NaN,NaN
62,62,B09Z7J4L6X,Xbox Wireless Controller – Sky Cipher Special ...,$69.99,NaN,USD,2.6,12,https://www.amazon.com/dp/B09Z7J4L6X,https://m.media-amazon.com/images/I/71i2tEKlZ2...,...,True,False,False,False,"Aug 13, 2024",FREE deliveryThis item will be released on Aug...,False,NaN,NaN,NaN
63,63,B0CT2R7199,HP DeskJet 2855e Wireless All-in-One Color Ink...,$59.99,$84.99,USD,4.0,48154,https://www.amazon.com/dp/B0CT2R7199,https://m.media-amazon.com/images/I/61+biEwB1h...,...,True,False,False,True,80K+ bought in past month,FREE delivery,False,NaN,NaN,NaN

In [12]:
data.head(2) # usamos la funcion head para ver las primeras 2 filas del dataframe

,Unnamed: 0,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
0,0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,...,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
1,1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,...,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False,Only 7 left in stock - order soon.,NaN,NaN

In [15]:
type(data["product_price"][0])

str

In [17]:
data.columns # usamos la funcion columns para ver las columnas del dataframe

Index(['Unnamed: 0', 'asin', 'product_title', 'product_price',
       'product_original_price', 'currency', 'product_star_rating',
       'product_num_ratings', 'product_url', 'product_photo',
       'product_num_offers', 'product_minimum_offer_price', 'is_best_seller',
       'is_amazon_choice', 'is_prime', 'climate_pledge_friendly',
       'sales_volume', 'delivery', 'has_variations', 'product_availability',
       'unit_price', 'unit_count'],
      dtype='str')

In [19]:
data.info() # usamos la funcion info para ver la informacion del dataframe

<class 'pandas.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   64 non-null     int64
 1   asin                         64 non-null     str
 2   product_title                64 non-null     str
 3   product_price                64 non-null     str
 4   product_original_price       27 non-null     str
 5   currency                     64 non-null     str
 6   product_star_rating          54 non-null     float64
 7   product_num_ratings          64 non-null     int64
 8   product_url                  64 non-null     str
 9   product_photo                64 non-null     str
 10  product_num_offers           64 non-null     int64
 11  product_minimum_offer_price  64 non-null     str
 12  is_best_seller               64 non-null     bool
 13  is_amazon_choice             64 non-null     bool
 14  is_prime                     64 non-null     bool
 15  climate_pledge_friendly      64 non-null     bool
 16  sales_volume                 61 non-null     str
 17  delivery                     63 non-null     str
 18  has_variations               64 non-null     bool
 19  product_availability         1 non-null      str
 20  unit_price                   5 non-null      str
 21  unit_count                   5 non-null      float64
dtypes: bool(5), float64(2), int64(3), str(12)
memory usage: 26.8 KB

#VAMOS A ELIMINAR COLUMNAS REDUNTANTES
#RENOMBRAR COLUMNAS
#ELIMINAR DUPLICADOS
#BUSCAR MAS TRANSFORMACIONES

In [22]:
data.columns

Index(['Unnamed: 0', 'asin', 'product_title', 'product_price',
       'product_original_price', 'currency', 'product_star_rating',
       'product_num_ratings', 'product_url', 'product_photo',
       'product_num_offers', 'product_minimum_offer_price', 'is_best_seller',
       'is_amazon_choice', 'is_prime', 'climate_pledge_friendly',
       'sales_volume', 'delivery', 'has_variations', 'product_availability',
       'unit_price', 'unit_count'],
      dtype='str')

In [ ]:
data.drop (columns = ['Unnamed: 0', 'asin','product_url', 'product_photo',
       'product_num_offers', 'product_minimum_offer_price','is_amazon_choice',
         'is_prime', 'climate_pledge_friendly','sales_volume', 'delivery', 'has_variations',], inplace = True) # usamos la funcion drop para eliminar columnas del dataframe

In [38]:
data.columns

Index(['Product_title', 'Product_price', 'Product_original_price', 'Currency',
       'Product_star_rating', 'Product_num_ratings', 'Is_best_seller',
       'Product_availability', 'Unit_price', 'Unit_count'],
      dtype='str')

Vamos a renombrar las columnas poniendoles mayusculas a la primera letra

In [ ]:

data_new_column_names = []

for x in data.columns:
    data_new_column_names.append(x.capitalize())

In [ ]:
data.columns =data_new_column_names #asiganamos los nuevos nombres de columnas al dataframe

In [40]:
data.head(2)#verificamos los cambios

,Product_title,Product_price,Product_original_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller,Product_availability,Unit_price,Unit_count
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,False,NaN,NaN,NaN
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,False,Only 7 left in stock - order soon.,NaN,NaN

VAMOS A ELIMINAR LOS DUPLICADOS DEL DATASET

In [42]:
data.duplicated().sum() # usamos la funcion duplicated para ver si hay filas duplicadas en el dataframe

np.int64(0)

VAMOS A ELIMINAR NA VALUES

In [44]:
data.isna().sum() # usamos la funcion isna para ver si hay valores nulos en el dataframe

Product_title              0
Product_price              0
Product_original_price    37
Currency                   0
Product_star_rating       10
Product_num_ratings        0
Is_best_seller             0
Product_availability      63
Unit_price                59
Unit_count                59
dtype: int64

In [47]:
data.shape # usamos la funcion shape para ver el tamaño del dataframe

(64, 10)

In [52]:
#como hay muchos valores nulos para tan pocos registros vamos a tomar solo las columnas que nos sirve

data = data[["Product_title", "Product_price", "Currency", "Product_star_rating", "Product_num_ratings", "Is_best_seller"]]
data

,Product_title,Product_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,USD,4.0,2929,False
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,USD,4.2,135,False
2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,USD,3.9,205,False
3,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,USD,4.3,2248,False
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,USD,4.1,423,False
...,...,...,...,...,...,...
59,Greatish Hits: I Followed My Dreams and My Dre...,$34.98,USD,NaN,0,False
60,Swan Song,$14.99,USD,4.4,14471,True
61,Bluey: Let&#x27;s Play!,$0.00,USD,3.5,270,False
62,Xbox Wireless Controller – Sky Cipher Special ...,$69.99,USD,2.6,12,True
63,HP DeskJet 2855e Wireless All-in-One Color Ink...,$59.99,USD,4.0,48154,True

In [54]:
data.isna().sum() # usamos la funcion isna para ver si hay valores nulos en el dataframe

Product_title           0
Product_price           0
Currency                0
Product_star_rating    10
Product_num_ratings     0
Is_best_seller          0
dtype: int64

In [56]:
data.dropna(inplace = True) # usamos la funcion dropna para eliminar filas con valores nulos del dataframe

In [58]:
data.isna().sum() # usamos la funcion isna para verificar si hay valores nulos en el dataframe

Product_title          0
Product_price          0
Currency               0
Product_star_rating    0
Product_num_ratings    0
Is_best_seller         0
dtype: int64

VAMOS A VERIFICAR SI PODEMOS HACER MAS CAMBIOS

In [60]:
data.head(3)

,Product_title,Product_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,USD,4.0,2929,False
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,USD,4.2,135,False
2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,USD,3.9,205,False

vAMOS A TRANSFORMAR LOS VALORES DE LA COLUMNA Product_price A TIPO FLOAT PARA PODER HACER ANALISIS DE DATOS

In [ ]:
data["Product_price"]= data["Product_price"].str.replace("$", "").astype(float) # usamos la funcion str.replace para eliminar el simbolo de dolar y luego usamos astype para convertir la columna a tipo float

In [69]:
data.head(2)

,Product_title,Product_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,99.99,USD,4.0,2929,False
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",149.74,USD,4.2,135,False

VAMOS A TRANSFORMAR LOS DATOS DE LA COLUMNA is_best_seller asignando valores como 0 y 1

In [71]:
data["Is_best_seller"]= data["Is_best_seller"].apply(lambda x: 1 if x == True else 0) # usamos la funcion apply para aplicar una funcion lambda a la columna Is_best_seller y convertir los valores True y False a 1 y 0 respectivamente

In [77]:
data

,Product_title,Product_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,99.99,USD,4.0,2929,0
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",149.74,USD,4.2,135,0
2,Total by Verizon | Samsung Galaxy A03s | Locke...,49.88,USD,3.9,205,0
3,Google Pixel 7a - Unlocked Android Cell Phone ...,335.00,USD,4.3,2248,0
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",199.99,USD,4.1,423,0
5,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",129.99,USD,4.2,578,0
6,"SAMSUNG Galaxy A35 5G A Series Cell Phone, 128...",349.99,USD,4.4,109,0
7,TracFone | Motorola Moto g Pure | Locked | 32G...,49.39,USD,4.2,2771,0
8,"SAMSUNG,Galaxy A04e (SM-A042M/DS) Dual SIM 32G...",87.10,USD,3.9,613,0
9,Moto G Play | 2024 | Unlocked | Made for US 4/...,129.99,USD,4.1,94,0
10,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...",70.61,USD,3.9,462,0
11,AT&amp;T BL102-2 DECT 6.0 2-Handset Cordless P...,48.75,USD,4.3,26685,1
12,Bold K10 | 2024 | 3-Day Battery | Unlocked | 6...,99.99,USD,3.8,8,0
13,Google Pixel 8 - Unlocked Android Smartphone w...,499.00,USD,4.3,2098,0
14,Motorola Moto G Power 5G | 2023 | Unlocked | M...,199.99,USD,4.2,2258,0
15,VTech CS6719-2 2-Handset Expandable Cordless P...,38.67,USD,4.4,37513,0
16,Apple AirTag,23.99,USD,4.6,4355,0
17,Apple AirTag 4 pack,84.99,USD,4.7,390,0
18,"Amazon Basics - Washable School Glue Sticks, D...",0.25,USD,4.7,8010,0
19,Amazon Basics Heavy Duty Plastic Folders with ...,0.49,USD,4.8,13638,1
20,"Amazon Basics Multipurpose, Comfort Grip, PVD ...",2.39,USD,4.8,54922,1
21,The Book of Bill (Gravity Falls),18.09,USD,4.7,180,1
23,Peacock TV,0.00,USD,4.2,437768,0
24,Thanksgiving - UHD/BD Combo + Digital + Steelb...,55.99,USD,4.0,3075,1
25,"NESCAFÉ Gold Espresso Blonde, Instant Coffee, ...",6.68,USD,4.7,628,1
26,Hillbilly Elegy: A Memoir of a Family and Cult...,11.53,USD,4.4,100331,1
29,URO Vaginal Probiotics for Women pH Balance wi...,28.79,USD,4.5,1142,1
30,Going Balls: 3D Race,0.00,USD,4.7,8,0
31,Atomic Habits: An Easy &amp; Proven Way to Bui...,0.00,USD,4.8,130395,1
33,The Anxious Generation: How the Great Rewiring...,0.00,USD,4.7,2317,1
35,DAYBETTER LED Strip Lights 130ft (2 Rolls of 6...,12.99,USD,4.5,27686,0
36,Teacher Simulator: School Days,0.00,USD,3.2,9,0
37,"Bounty Select-A-Size Paper Towels, White, 8 Tr...",22.18,USD,4.8,36930,0
38,Apple AirPods Pro (2nd Generation) Wireless Ea...,179.99,USD,4.6,2687,0
39,Rand McNally Large Scale Road Atlas 2025,19.02,USD,4.7,793,1
41,EA SPORTS College Football 25 - PlayStation 5,67.28,USD,3.8,96,1
42,My Avatar Life City,0.00,USD,1.8,12,0
43,Max,0.00,USD,4.3,384756,0
44,Ragdoll Kick: Broken Bones,0.00,USD,4.4,38,0
45,It Ends with Us,0.00,USD,4.7,333273,1
47,What Now,11.99,USD,4.2,51,1
48,All the Colors of the Dark,0.00,USD,4.6,6346,1
49,In A Violent Nature: Collector’s Edition [Blu-...,29.99,USD,3.2,204,0
50,The God of the Woods: A Novel,14.99,USD,4.5,3241,1
51,"Hanes Men&#x27;s Pocket Undershirt Pack, Cotto...",22.00,USD,4.4,25391,0
54,Mission: Impossible - Dead Reckoning,5.99,USD,4.7,2440,0
55,Disney+,0.00,USD,4.4,1015448,0
56,Netflix,0.00,USD,4.6,447888,0
57,A Death in Cornwall: A Novel (Gabriel Allon Bo...,15.99,USD,4.6,7384,1
58,TikTok,0.00,USD,4.2,140637,0
60,Swan Song,14.99,USD,4.4,14471,1
61,Bluey: Let&#x27;s Play!,0.00,USD,3.5,270,0
62,Xbox Wireless Controller – Sky Cipher Special ...,69.99,USD,2.6,12,1
63,HP DeskJet 2855e Wireless All-in-One Color Ink...,59.99,USD,4.0,48154,1

In [78]:
data.to_excel("Amazon_products_cleaned.xlsx", index = False) # usamos la funcion to_excel para guardar el dataframe en un archivo excel

In [79]:
data.to_csv("Amazon_products_cleaned.csv", index = False) # usamos la funcion to_csv para guardar el dataframe en un archivo csv